### ISSUE TITLE
How to run the scheme, i.e. '.json' file, synthesized by SCCL on NCCL ?

### ISSUE THREAD

**Issue by oliverYoung2001** [microsoft/msccl-tools#50]
I use SCCL to synthesize a step=3 alltoall algorithm on topology DGX-1 whose name is ’Alltoall.n8-DGX1-steps3.msccl.json‘. But how can I actually run it on NCCL ? Can you give me an example or a document about how to actually run a synthesized scheme ? Thanks a lot !

**Comment by saeedmaleki** [comment]
Try `msccl ncclize <file.json>`

**Comment by oliverYoung2001** [comment]
It works, thanks !
